version: '3.8'

services:
  blueastowel:
    image: sayinmehmet47/client-blueastowel
    ports:
      - '3000:3000'
    environment:
      - PAYLOAD_APP_URL=http://payload:3000
      - PAYLOAD_API_KEY=2465a770-bc55-437e-8736-65f6f4e1b6ad
      - PAYLOAD_API_SLUG=users
      - URL=http://blueastowel:3000
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - payload

  payload:
    image: sayinmehmet47/payload-cms-app:latest
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    volumes:
      - payload-data:/home/node/app/dist/media
    environment:
      - DATABASE_URI=mongodb://mongo/payload-template-blank
      - PAYLOAD_SECRET=YOUR_SECRET_HERE
      - SMTP_USER=blueastowel92@gmail.com
      - SMTP_PASS=mpqj dgus jrgu qnil

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    command: ['--storageEngine=wiredTiger']
    logging:
      driver: none

volumes:
  data:
  node_modules:
  payload-data:

networks:
  app-network:
    driver: bridge
