version: '3.8'

services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - /root/blueastowel/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - /etc/letsencrypt:/etc/letsencrypt
  #   networks:
  #     - app-network
  #   depends_on:
  #     - blueastowel
  #     - payload

  blueastowel:
    image: sayinmehmet47/client-blueastowel
    ports:
      - '3000:3000'
    environment:
      - PAYLOAD_APP_URL=http://payload:3000
      - PAYLOAD_API_KEY=50ab8231-770c-4fb9-9ec5-e1ce67650270
      - PAYLOAD_API_SLUG=users
      - URL=http://blueastowel:3000
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - payload

  payload:
    image: sayinmehmet47/payload-cms-app:latest
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    environment:
      - DATABASE_URI=mongodb://mongo/payload-template-blank
      - PAYLOAD_SECRET=YOUR_SECRET_HERE
      - SMTP_USER=blueastowel92@gmail.com
      - SMTP_PASS=rqmr tacp imuq xgvj
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    command: ["--storageEngine=wiredTiger"]
    logging:
      driver: none
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
