name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.HETZNER_KEY }}

    - name: Rsync files to server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i /root/blueastowel/hetzner_key.pem" --exclude node_modules --exclude .next . ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }}:/root/blueastowel

    - name: Install dependencies and build on server
      run: |
        ssh -o StrictHostKeyChecking=no -i /root/blueastowel/hetzner_key.pem ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }} << 'EOF'
          cd /root/blueastowel
          npm install
          npm run build
          npm install pm2 -g  # Ensure PM2 is installed
          pm2 restart all || pm2 start npm --name "blueastowel" -- start
        EOF
