name: deploy-payload

on:
  push:
    branches:
      - main
    paths:
      - 'payload-cms/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: payload-cms/
          platforms: linux/amd64
          push: true
          tags: sayinmehmet47/payload-cms-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HETZNER_KEY }}
      
      - name: Deploy new image to Hetzner and restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }} << 'EOF'
            cd /root/blueastowel-payload-cms
            docker-compose down
            docker-compose pull
            docker-compose up -d
            sudo systemctl restart nginx
          EOF
